language: scala

script:
  - sbt scalastyle && sbt test:scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport && sbt coverageAggregate

matrix:
  include:
    - jdk: oraclejdk9
      scala: 2.11.11
    - jdk: oraclejdk9
      scala: 2.12.6

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

after_success:
  - sbt coveralls

